const ACTION_TYPES = {
  /**
   * Authentication
   */
  // login
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_RESPONSE: 'LOGIN_RESPONSE',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_CLEAR: 'LOGIN_CLEAR',

  GET_LINEITEM_REQUEST: 'GET_LINEITEM_REQUEST',
  GET_LINEITEM_RESPONSE: 'GET_LINEITEM_RESPONSE',
  GET_LINEITEM_ERROR: 'GET_LINEITEM_ERROR',
  GET_LINEITEM_CLEAR: 'GET_LINEITEM_CLEAR',

  POST_IMAGEVIDEO_LINEITEM_REQUEST: 'POST_IMAGEVIDEO_LINEITEM_REQUEST',
  POST_IMAGEVIDEO_LINEITEM_RESPONSE: 'POST_IMAGEVIDEO_LINEITEM_RESPONSE',
  POST_IMAGEVIDEO_LINEITEM_ERROR: 'POST_IMAGEVIDEO_LINEITEM_ERROR',
  POST_IMAGEVIDEO_LINEITEM_CLEAR: 'POST_IMAGEVIDEO_LINEITEM_CLEAR',

  POST_VIDEO_LINEITEM_REQUEST: 'POST_VIDEO_LINEITEM_REQUEST',
  POST_VIDEO_LINEITEM_RESPONSE: 'POST_VIDEO_LINEITEM_RESPONSE',
  POST_VIDEO_LINEITEM_ERROR: 'POST_VIDEO_LINEITEM_ERROR',
  POST_VIDEO_LINEITEM_CLEAR: 'POST_VIDEO_LINEITEM_CLEAR',

  //All Inspection
  //All inspection List view
  ALL_INSPECTION_LIST_REQUEST: 'ALL_INSPECTION_LIST_REQUEST',
  ALL_INSPECTION_LIST_RESPONSE: 'ALL_INSPECTION_LIST_RESPONSE',
  ALL_INSPECTION_LIST_ERROR: 'ALL_INSPECTION_LIST_ERROR',
  ALL_INSPECTION_LIST_CLEAR: 'ALL_INSPECTION_LIST_CLEAR',

};

export default ACTION_TYPES;
