/**
 * Redux constants for Category list Redux
 * @author Vivek PS
 */
const CATEGORY_REDUX_ACTION_TYPES = {
    UPDATE_CATEGORY_LIST_REQUEST: 'UPDATE_CATEGORY_LIST_REQUEST',
    UPDATE_CATEGORY_LIST_RESPONSE: 'UPDATE_CATEGORY_LIST_RESPONSE',
    UPDATE_CATEGORY_LIST_ERROR: 'UPDATE_CATEGORY_LIST_ERROR',
    UPDATE_CATEGORY_LIST_CLEAR: 'UPDATE_CATEGORY_LIST_CLEAR',
}

export default CATEGORY_REDUX_ACTION_TYPES
