// Redux constants for the Galley
export const ADD_IMAGES_TO_GALLERY = 'ADD_IMAGES_TO_GALLERY';
export const DELETE_IMAGES_FROM_GALLERY = 'DELETE_IMAGES_FROM_GALLERY';
export const UPDATE_GALLERY_IMAGES = 'UPDATE_GALLERY_IMAGES';
