/**
 * Redux constants for LineItem Redux
 * @author Charles
 */
const INSPECTION_REDUX_ACTION_TYPES = {
  ALL_INSPECTION_LIST_REQUEST: 'ALL_INSPECTION_LIST_REQUEST',
  ALL_INSPECTION_LIST_RESPONSE: 'ALL_INSPECTION_LIST_RESPONSE',
  ALL_INSPECTION_LIST_ERROR: 'ALL_INSPECTION_LIST_ERROR',
  ALL_INSPECTION_LIST_CLEAR: 'ALL_INSPECTION_LIST_CLEAR',
};

export default INSPECTION_REDUX_ACTION_TYPES;
