const INSPECTION_REDUCER_ACTION_TYPES = {
    //All Inspection

    //Inspection Details
    GET_INSPECTION_DETAILS_REQUEST: 'GET_INSPECTION_DETAILS_REQUEST',
    GET_INSPECTION_DETAILS_RESPONSE: 'GET_INSPECTION_DETAILS_RESPONSE',
    GET_INSPECTION_DETAILS_ERROR: 'GET_INSPECTION_DETAILS_ERROR',
    GET_INSPECTION_DETAILS_CLEAR: 'GET_INSPECTION_DETAILS_CLEAR',


    // Date based inspection List
    DATE_BASED_INSPECTION_LIST_REQUEST: 'DATE_BASED_INSPECTION_LIST_REQUEST',
    DATE_BASED_INSPECTION_LIST_RESPONSE: 'DATE_BASED_INSPECTION_LIST_RESPONSE',
    DATE_BASED_INSPECTION_LIST_ERROR: 'DATE_BASED_INSPECTION_LIST_ERROR',
    DATE_BASED_INSPECTION_LIST_CLEAR: 'DATE_BASED_INSPECTION_LIST_CLEAR',
};

export default INSPECTION_REDUCER_ACTION_TYPES;
