/**
 * Redux constants for LineItem Redux
 * @author Charles
 */
const LINEITEM_REDUX_ACTION_TYPES = {
  GET_LINEITEM_REQUEST: 'GET_LINEITEM_REQUEST',
  GET_LINEITEM_RESPONSE: 'GET_LINEITEM_RESPONSE',
  GET_LINEITEM_ERROR: 'GET_LINEITEM_ERROR',
  GET_LINEITEM_CLEAR: 'GET_LINEITEM_CLEAR',

  GET_LINEINPUT_CONTROLS_REQUEST: 'GET_LINEINPUT_CONTROLS_REQUEST',
  GET_LINEINPUT_CONTROLS_RESPONSE: 'GET_LINEINPUT_CONTROLS_RESPONSE',
  GET_LINEINPUT_CONTROLS_ERROR: 'GET_LINEINPUT_CONTROLS_ERROR',
  GET_LINEINPUT_CONTROLS_CLEAR: 'GET_LINEINPUT_CONTROLS_CLEAR',

  GET_INSPECTION_DATA_REQUEST: 'GET_INSPECTION_DATA_REQUEST',
  GET_INSPECTION_DATA_RESPONSE: 'GET_INSPECTION_DATA_RESPONSE',
  GET_INSPECTION_DATA_ERROR: 'GET_INSPECTION_DATA_ERROR',
  GET_INSPECTION_DATA_CLEAR: 'GET_INSPECTION_DATA_CLEAR',

 STORE_LINEINPUT_CONTROLS_REQUEST: 'STORE_LINEINPUT_CONTROLS_REQUEST',
  STORE_LINEINPUT_CONTROLS_RESPONSE: 'STORE_LINEINPUT_CONTROLS_RESPONSE',
  STORE_LINEINPUT_CONTROLS_ERROR: 'STORE_LINEINPUT_CONTROLS_ERROR',
  STORE_LINEINPUT_CONTROLS_CLEAR: 'STORE_LINEINPUT_CONTROLS_CLEAR',
};

export default LINEITEM_REDUX_ACTION_TYPES;
